### ISSUE TITLE
Update GitHub Actions Workflow

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/drug-dictionary-api#60]
Update the GitHub workflow file to use .Net 3.1

**Parent Issue:**  Update the drug dictionary to .Net 3.1 #54 

## Set global environment variables

At the top of the workflow file, before the `jobs:` property, add a new `env:` property
```yaml
env:
  DOTNET_NOLOGO: true
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
```

## Update the `test_build_release:` job

* At the start of the job, add a new `env` setting:
```yaml
    env:
      OWNER: ${{ needs.extract_build_info.outputs.repo_owner }}
    runs-on: ${{ matrix.operating-system }}
```
* Change the checkout action to `- uses: actions/checkout@v2`
* Change the `setup-dotnet` action to:
  ```yaml
        ## using latest LTS releases - also it MUST be the SDK version.
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.*'
          source-url: "https://nuget.pkg.github.com/${{ env.OWNER }}/index.json"
  ```

## Update the `integration_tests:` job

* Change the checkout action to `- uses: actions/checkout@v2`
* Change the `setup-dotnet` action to:
  ```yaml
        ## using latest LTS releases - also it MUST be the SDK version.
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.*'
          source-url: "https://nuget.pkg.github.com/${{ env.OWNER }}/index.json"
  ```
